  if(!state.verifyFiles.length)return;const source=$('#verifySource').value;$('#runVerify').disabled=true;$('#runVerify').textContent='正在运行 4 Agent…';
  const analyses=[];
  for(const file of state.verifyFiles){const bitmap=await createImageBitmap(file);const a=await analyzeBitmap(bitmap,{useFace:true,statusCb:t=>$('#agentGuide h3').textContent=t});analyses.push({file,a})}
  const all=analyses.map(x=>x.a.lip||x.a.overall),sat=all.map(x=>x.saturation),br=all.map(x=>x.brightness),hue=all.map(x=>x.hue);const satRange=Math.max(...sat)-Math.min(...sat),brRange=Math.max(...br)-Math.min(...br),hueRange=Math.max(...hue.map(h=>circularHueDistance(h,median(hue))));
  const findings=[];for(const x of analyses){const m=x.a.lip||x.a.overall;if(m.saturation>75)findings.push(`${x.file.name}：饱和度 ${m.saturation}% 偏高`);if(m.brightness>80)findings.push(`${x.file.name}：亮度 ${m.brightness}% 偏高 / 可能过曝`);if(m.brightness<30)findings.push(`${x.file.name}：画面偏暗`);if(x.a.lighting.includes('偏暖')||x.a.lighting.includes('偏冷'))findings.push(`${x.file.name}：${x.a.lighting}`)}
  if(satRange>30)findings.push(`多图饱和度范围相差 ${round(satRange)}%`);if(brRange>35)findings.push(`多图亮度范围相差 ${round(brRange)}%`);if(hueRange>60)findings.push(`多图色相差异较大`);
  let penalty=findings.length*2+(hueRange>60?4:0),score=Math.max(25,Math.min(95,82-penalty));
  const html=`<div class="agent-results"><article class="agent-card"><div class="agent-head"><h3>01 · 色彩分析师</h3><small>真实像素分析完成</small></div><p>${analyses.filter(x=>x.a.lip).length}/${analyses.length} 张图成功识别唇部 ROI；其余使用整图色彩作为低置信度参考。</p><div class="finding-list">${analyses.map(x=>{const m=x.a.lip||x.a.overall;return `<div class="finding"><b>${escapeHtml(x.file.name)}</b> · H ${m.hue}° / S ${m.saturation}% / B ${m.brightness}% · ${x.a.lighting}</div>`}).join('')}</div></article><article class="agent-card"><div class="agent-head"><h3>02 · 鉴伪审查员</h3><small>参考可信度 ${score}/100</small></div><p>当前结论只描述“视觉偏差风险”，不把差异直接等同于 P 图。</p><div class="finding-list">${findings.length?findings.map(f=>`<div class="finding">${escapeHtml(f)}</div>`).join(''):'<div class="finding">当前没有触发明显异常阈值。</div>'}</div></article><article class="agent-card"><div class="agent-head"><h3>03 · 报告撰写员</h3><small>消费者视角</small></div><p>${score>=80?'这组试色整体较稳定，可作为辅助参考。':score>=60?'这组试色存在一些拍摄/颜色差异，建议优先参考光照稳定且唇部清晰的图片。':'当前样本差异较大，不建议仅凭这组图片做购买决定。'}</p></article><article class="agent-card"><div class="agent-head"><h3>04 · 创作者顾问</h3><small>如何让内容更可信</small></div><div class="finding-list"><div class="finding">补充自然光或中性光版本，并标注拍摄条件。</div><div class="finding">增加素唇对比和薄涂 / 厚涂对比。</div><div class="finding">若做了后期，请避免局部增饱和，并保留无滤镜原图。</div></div></article></div>`;
  $('#verifyResults').innerHTML=html;$('#verifyResults').classList.remove('hidden');$('#runVerify').disabled=false;$('#runVerify').textContent='重新运行分析';$('#agentGuide h3').textContent='这次分析会发生什么？';$('#verifyResults').scrollIntoView({behavior:'smooth'});
}

async function runSelfie(){
  if(!state.selfieFile)return;const p=productByKey(state.selfieShade),d=await loadProduct(p.key);$('#runSelfie').disabled=true;$('#runSelfie').textContent='正在分析自拍…';
  const bitmap=await createImageBitmap(state.selfieFile);const a=await analyzeBitmap(bitmap,{useFace:true,statusCb:t=>$('#modelStatus').textContent=t});state.selfieAnalysis=a;
  const ref=Object.values(d.visual_sample.source_stats);const hue=median(ref.map(x=>x.hue)),sat=median(ref.map(x=>x.saturation));state.selfieTryon=a.lipMask?applyVirtualLip(a.canvas,a.lipMask,hue,Math.max(30,Math.min(60,sat+8))):null;drawSelfieCanvas('original');
  const faceHex=a.faceColor?canvasToHex(a.faceColor):null;const personal=rankPersonalEvidence(d,{lip:state.selfieLip,style:null,finish:null}).slice(0,3);
  $('#selfieResults').innerHTML=`<div class="selfie-report"><div class="result-tile"><h4>① 当前自拍质量</h4><p>${a.quality}${a.faces?` · 检测到 ${a.faces} 张脸，已选择面积最大的人脸`:''}</p></div><div class="result-tile"><h4>② 当前拍摄光照</h4><p>${a.lighting}。结果只代表当前照片的拍摄环境。</p></div><div class="result-tile"><h4>③ 面部颜色参考</h4>${faceHex?`<div class="color-dot" style="background:${faceHex}"></div><p>${faceHex} · 仅代表当前照片可见颜色，不是永久肤色结论。</p>`:'<p>当前无法稳定提取面部参考颜色。</p>'}</div><div class="result-tile"><h4>④ TrueTone 参考色域</h4><div class="spectrum-mini">${[-8,-4,0,4,8].map(x=>`<i style="background:${hueHex((hue+x+360)%360,38,68)}"></i>`).join('')}</div><p>${p.brand} #${p.shade}</p></div><div class="result-tile wide"><h4>⑤ 在当前自拍中的预计呈现</h4><p>${a.lip?`根据当前唇部与多来源参考色域，#${p.shade} 可能呈现为 ${hue<18?'偏红棕':hue<40?'偏奶茶/豆沙':'偏冷调'}，当前光照为“${a.lighting}”，因此最终观感可能与网络主流试色有差异。`:'未能稳定识别唇部，因此不生成强个性化颜色结论。建议换一张正脸、嘴唇清晰的自然光自拍。'}</p></div><div class="result-tile wide"><h4>⑥ 你最应该参考哪些真实反馈？</h4>${personal.map(r=>`<p>• ${highlight(r.text.slice(0,180))} <small>— ${escapeHtml(r.source)}</small></p>`).join('')}</div><div class="result-tile"><h4>⑦ 虚拟试色</h4><p>${state.selfieTryon?'已生成：仅改变唇部色相/饱和度并保留原始明暗纹理。':'未生成：唇部定位不稳定时不会强行做假预览。'}</p></div><div class="result-tile"><h4>⑧ 购买前建议</h4><p>优先参考与你当前唇色、光照条件相近的真实返图；虚拟试色仅为视觉模拟，不代表实物最终效果。</p></div></div>`;
  $('#selfieResults').classList.remove('hidden');$('#runSelfie').disabled=false;$('#runSelfie').textContent='重新分析当前自拍';$('#selfieResults').scrollIntoView({behavior:'smooth'});
}
function drawSelfieCanvas(mode){const canvas=$('#selfieCanvas'),src=mode==='tryon'&&state.selfieTryon?state.selfieTryon:state.selfieAnalysis?.canvas;if(!src)return;canvas.width=src.width;canvas.height=src.height;canvas.getContext('2d').drawImage(src,0,0)}

async function runCompare(){const a=$('#compareA').value,b=$('#compareB').value;if(a===b)return;const [da,db]=await Promise.all([loadProduct(a),loadProduct(b)]);const ra=runDatasetAgents(da,{}),rb=runDatasetAgents(db,{});$('#compareResults').innerHTML=`<div class="compare-table">${[[a,da,ra],[b,db,rb]].map(([k,d,r])=>{const p=productByKey(k),s=d.visual_sample.source_stats;return `<article class="compare-card"><span class="eyebrow">${escapeHtml(p.brand)}</span><h2>#${p.shade}</h2><p>${escapeHtml(p.display)} · ${escapeHtml(p.finish)}</p><div class="compare-stat"><span>TrueTone 参考可信度</span><b>${Math.round(r.agent2.score)}/100</b></div><div class="compare-stat"><span>证据充分度</span><b>${r.agent2.suff}</b></div><div class="compare-stat"><span>小红书图片 / 淘宝图片</span><b>${d.counts.xhs_images} / ${d.counts.taobao_images}</b></div><div class="compare-stat"><span>环形 Hue 平台差</span><b>${round(r.agent1.hueDiff)}°</b></div><div class="compare-stat"><span>色差关键词最多</span><b>${Object.entries(d.keyword_counts).sort((x,y)=>y[1]-x[1])[0]?.[0]||'—'}</b></div><p>${escapeHtml(r.agent3.summary)}</p></article>`}).join('')}</div>`}

function setupSearch(){const input=$('#shadeSearch'),sug=$('#searchSuggestions');const render=()=>{const q=input.value.trim().toLowerCase();if(!q){sug.innerHTML='';return}const hits=CATALOG.filter(p=>`${p.label} ${p.brand} ${p.shade} ${p.display}`.toLowerCase().includes(q));sug.innerHTML=hits.map(p=>`<button data-product="${p.key}">${escapeHtml(p.brand)} #${p.shade} · ${escapeHtml(p.display)}</button>`).join('');$$('#searchSuggestions [data-product]').forEach(b=>b.onclick=()=>openProduct(b.dataset.product))};input.oninput=render;$('#searchBtn').onclick=()=>{const q=input.value.trim().toLowerCase();const p=CATALOG.find(x=>`${x.label} ${x.brand} ${x.shade} ${x.display}`.toLowerCase().includes(q))||CATALOG[0];openProduct(p.key)}}
function setupVerifyUpload(){const input=$('#verifyFiles'),zone=$('#verifyDropzone');const setFiles=files=>{state.verifyFiles=[...files].filter(f=>f.type.startsWith('image/'));renderVerifyPreviews()};input.onchange=e=>setFiles(e.target.files);zone.ondragover=e=>{e.preventDefault();zone.classList.add('drag')};zone.ondragleave=()=>zone.classList.remove('drag');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('drag');setFiles(e.dataTransfer.files)};$('#runVerify').onclick=runVerify}
function renderVerifyPreviews(){const wrap=$('#verifyPreviews');wrap.innerHTML='';state.verifyFiles.forEach((f,i)=>{const u=URL.createObjectURL(f);wrap.insertAdjacentHTML('beforeend',`<div class="preview-item"><img src="${u}"><button data-i="${i}">×</button></div>`)});$$('#verifyPreviews button').forEach(b=>b.onclick=()=>{state.verifyFiles.splice(Number(b.dataset.i),1);renderVerifyPreviews()});$('#runVerify').disabled=!state.verifyFiles.length}
function setupSelfie(){
  $('#selfieShadeOptions').innerHTML=CATALOG.map((p,i)=>`<button class="shade-option ${i===0?'active':''}" data-key="${p.key}"><b>${p.brand} #${p.shade}</b><small>${p.display}</small></button>`).join('');$$('.shade-option').forEach(b=>b.onclick=()=>{$$('.shade-option').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.selfieShade=b.dataset.key});
  $('#selfieFile').onchange=e=>{const f=e.target.files[0];if(!f)return;state.selfieFile=f;const img=new Image();img.onload=()=>{const c=$('#selfieCanvas');const max=1000,sc=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));c.width=img.naturalWidth*sc;c.height=img.naturalHeight*sc;c.getContext('2d').drawImage(img,0,0,c.width,c.height);$('#selfieDropzone').classList.add('hidden');$('#selfieCanvasWrap').classList.remove('hidden');$('#runSelfie').disabled=false;URL.revokeObjectURL(img.src)};img.src=URL.createObjectURL(f)};
  $$('#selfieLipProfile button').forEach(b=>b.onclick=()=>{$$('#selfieLipProfile button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.selfieLip=b.dataset.value});
  $('#runSelfie').onclick=runSelfie;$$('[data-canvas-mode]').forEach(b=>b.onclick=()=>{$$('[data-canvas-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');drawSelfieCanvas(b.dataset.canvasMode)})
}
async function preloadCatalog(){await Promise.all(CATALOG.map(p=>loadProduct(p.key)));$('#compareA').innerHTML=CATALOG.map((p,i)=>`<option value="${p.key}" ${i===0?'selected':''}>${p.brand} #${p.shade}</option>`).join('');$('#compareB').innerHTML=CATALOG.map((p,i)=>`<option value="${p.key}" ${i===2?'selected':''}>${p.brand} #${p.shade}</option>`).join('')}

function bind(){
  $$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$$('[data-nav]').forEach(b=>b.onclick=()=>showView(b.dataset.nav));$$('[data-product]').forEach(b=>b.onclick=()=>openProduct(b.dataset.product));
  $('#runShadeAnalysis').onclick=async()=>{const d=await loadProduct(state.product);const res=runDatasetAgents(d,state.profile);renderShadeReport(d,res)};
  $('#whyToggle').onclick=()=>$('#whyBox').classList.toggle('hidden');$('#techToggle').onclick=()=>$('#technicalEvidence').classList.toggle('hidden');
  $$('.chip-group[data-profile] button').forEach(b=>b.onclick=async()=>{const group=b.closest('.chip-group'),key=group.dataset.profile;group.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.profile[key]=b.dataset.value;if(state.product)renderMatched(await loadProduct(state.product))});
  $('#likeShade').onclick=()=>renderRecommendations(state.product,'similar');$('#dislikeShade').onclick=()=>{$('#recommendations').classList.remove('hidden');$('#recommendations').innerHTML='<p class="eyebrow">你希望往哪个方向调？</p><div class="decision-actions"><button class="ghost" data-dir="orange">更橘一点</button><button class="ghost" data-dir="clean">更干净 / 更稳妥</button><button class="ghost" data-dir="bold">更有气场</button></div>';$$('#recommendations [data-dir]').forEach(b=>b.onclick=()=>renderRecommendations(state.product,b.dataset.dir))};
  $('#runCompare').onclick=runCompare;setupSearch();setupVerifyUpload();setupSelfie();
}

(async function init(){bind();await preloadCatalog();const hash=location.hash.replace('#','');if(['verify','selfie','compare'].includes(hash))showView(hash);else showView('home')})();
